rhsm-conduit:
  org-sync:
    # The cron schedule is only used in development mode.  In a production deployment, a version of the
    # application with the "orgsync" profile is deployed and run as a one-shot job.  The scheduling
    # is handled by OpenShift's cron capabilities.
    schedule: ${ORG_SYNC_SCHEDULE:0 */2 * * * ?}
  rhsm:
    use-stub: ${RHSM_USE_STUB:false}
    url: ${RHSM_URL:http://localhost:9090}
    keystore-file: ${RHSM_KEYSTORE:}
    keystore-password: ${RHSM_KEYSTORE_PASSWORD:changeit}
    request-batch-size: ${RHSM_BATCH_SIZE:1000}
    max-connections: ${RHSM_MAX_CONNECTIONS:100}
  inventory-service:
    use-stub: ${INVENTORY_USE_STUB:true}
    api-key: ${INVENTORY_API_KEY:changeit}
    host-last-sync-threshold: ${INVENTORY_HOST_LAST_SYNC_THRESHOLD:24h}
    add-uuid-hyphens: ${INVENTORY_ADD_UUID_HYPHENS:false}
    # FIXME: misnamed, it's actually in hours
    stale-host-offset-in-days: ${INVENTORY_STALE_HOST_OFFSET_HOURS:48}
    kafka-host-ingress-topic: ${INVENTORY_HOST_INGRESS_TOPIC:platform.inventory.host-ingress}
  tasks:
    topic: ${CONDUIT_KAFKA_TOPIC:platform.rhsm-conduit.tasks}
    kafka-group-id: ${CONDUIT_KAFKA_GROUP_ID:rhsm-conduit-task-processor}
